import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";


import { ClerkProvider } from "@clerk/nextjs";
import LeftSidebar from "@/components/layout/LeftSidebar";
import Topbar from "@/components/layout/Topbar";
import ToasterProvider from "@/lib/ToasterProvider";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nextjs 14  - Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <div className="flex max-lg:flex-col text-grey-1">
              <ToasterProvider />
              <LeftSidebar />
              <Topbar />
              <div className="flex-1">
                {children}
              </div>
            </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
